version: '3.9'

volumes:
  PizzaRestourantMsSqlDbStorage:
  
services:
  MsSqlServer:
    container_name: "PizzaRestourantMsSqlDb"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    env_file:
      - sqlconfig.env
      - sapassword.env
    ports:
      - "1439:1433"
    volumes:
      - PizzaRestourantMsSqlDbStorage:/var/opt/mssql/