version: '3.9'

volumes:
  PizzaRestourantMsSqlDbStorage:

networks:
  my-network:
    driver: bridge
  
services:
  pizza-restourant-sqlserver:
    container_name: "PizzaRestourant.MsSqlDb"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    env_file:
      - sqlconfig.env
      - sapassword.env
    ports:
      - "1439:1433"
    volumes:
      - PizzaRestourantMsSqlDbStorage:/var/opt/mssql/
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "exec", "pidof", "sqlservr"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s